server:
  port: 10010
zuul:
  prefix: /api
  routes:
#    user-service: /user-service/**
#    user-service: /user/**
    user-service:
      path: /user/**
      serviceId: user-service
      strip-prefix: false
  ignored-services:
    consumer-service
#    hehe:
#      path: /user-service/**
#      serviceId: user-service
#      url: http://127.0.0.1:8081
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
spring:
  application:
    name: gateway
ribbon:
  ConnectionTimeout: 500
  ReadTimeOut: 2000
  MaxAutoRetriesNextServer: 0
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000