server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/szx_market?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 12345678
  application:
    name: user-service
mybatis:
  type-aliases-package: com.szx.user.pojo
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka